//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSpotApi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FishSpotResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FishSpotResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishSpotApi.Domain.Resources.FishSpotResource", typeof(FishSpotResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already in use.
        /// </summary>
        public static string email_in_use {
            get {
                return ResourceManager.GetString("email_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is authenticated.
        /// </summary>
        public static string is_authenticated {
            get {
                return ResourceManager.GetString("is_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string mail_verification_code {
            get {
                return ResourceManager.GetString("mail_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resources were attached to a spot.
        /// </summary>
        public static string resource_attached {
            get {
                return ResourceManager.GetString("resource_attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resources were detached to a spot.
        /// </summary>
        public static string resource_detached {
            get {
                return ResourceManager.GetString("resource_detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string resource_not_found {
            get {
                return ResourceManager.GetString("resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was caught when tried to detach the resources.
        /// </summary>
        public static string resource_unable_to_detach {
            get {
                return ResourceManager.GetString("resource_unable_to_detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save files.
        /// </summary>
        public static string resource_unable_to_save {
            get {
                return ResourceManager.GetString("resource_unable_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot deleted successfully.
        /// </summary>
        public static string spot_deleted_successfully {
            get {
                return ResourceManager.GetString("spot_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot find.
        /// </summary>
        public static string spot_find {
            get {
                return ResourceManager.GetString("spot_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations find.
        /// </summary>
        public static string spot_location_find {
            get {
                return ResourceManager.GetString("spot_location_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot not found.
        /// </summary>
        public static string spot_not_found {
            get {
                return ResourceManager.GetString("spot_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot registered successfully.
        /// </summary>
        public static string spot_registered_successfully {
            get {
                return ResourceManager.GetString("spot_registered_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot updated successfully.
        /// </summary>
        public static string spot_updated_successfully {
            get {
                return ResourceManager.GetString("spot_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validation token was sent to your e-mail.
        /// </summary>
        public static string token_email_sent {
            get {
                return ResourceManager.GetString("token_email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        public static string token_invalid {
            get {
                return ResourceManager.GetString("token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found.
        /// </summary>
        public static string token_not_found {
            get {
                return ResourceManager.GetString("token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string token_refresh_invalid {
            get {
                return ResourceManager.GetString("token_refresh_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed.
        /// </summary>
        public static string token_refreshed {
            get {
                return ResourceManager.GetString("token_refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is valid.
        /// </summary>
        public static string token_valid {
            get {
                return ResourceManager.GetString("token_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t authorized.
        /// </summary>
        public static string unauthorized {
            get {
                return ResourceManager.GetString("unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was correctly authenticated..
        /// </summary>
        public static string user_authenticated {
            get {
                return ResourceManager.GetString("user_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to delete spot.
        /// </summary>
        public static string user_not_authorized_to_delete_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_delete_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to update spot.
        /// </summary>
        public static string user_not_authorized_to_update_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_update_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string user_password_incorrect {
            get {
                return ResourceManager.GetString("user_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string user_register_successfully {
            get {
                return ResourceManager.GetString("user_register_successfully", resourceCulture);
            }
        }
    }
}
