//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSpotApi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FishSpotResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FishSpotResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishSpotApi.Domain.Resources.FishSpotResource", typeof(FishSpotResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates must be at most 2 characters long.
        /// </summary>
        public static string annotation_coordinates_max_length {
            get {
                return ResourceManager.GetString("annotation_coordinates_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates must be at least 2 characters long.
        /// </summary>
        public static string annotation_coordinates_min_length {
            get {
                return ResourceManager.GetString("annotation_coordinates_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates must be filled.
        /// </summary>
        public static string annotation_coordinates_required {
            get {
                return ResourceManager.GetString("annotation_coordinates_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be filled.
        /// </summary>
        public static string annotation_date_required {
            get {
                return ResourceManager.GetString("annotation_date_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_description_max_length {
            get {
                return ResourceManager.GetString("annotation_description_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must be filled.
        /// </summary>
        public static string annotation_description_required {
            get {
                return ResourceManager.GetString("annotation_description_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_email_max_length {
            get {
                return ResourceManager.GetString("annotation_email_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail must be filled.
        /// </summary>
        public static string annotation_email_required {
            get {
                return ResourceManager.GetString("annotation_email_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail it not valid.
        /// </summary>
        public static string annotation_email_validation {
            get {
                return ResourceManager.GetString("annotation_email_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of 30 files has been reached.
        /// </summary>
        public static string annotation_files_max_length {
            get {
                return ResourceManager.GetString("annotation_files_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of file id must be at least one.
        /// </summary>
        public static string annotation_files_min_length {
            get {
                return ResourceManager.GetString("annotation_files_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list with file must be filled.
        /// </summary>
        public static string annotation_files_required {
            get {
                return ResourceManager.GetString("annotation_files_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of fishes required.
        /// </summary>
        public static string annotation_fishs_min_length {
            get {
                return ResourceManager.GetString("annotation_fishs_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of lures has been reached.
        /// </summary>
        public static string annotation_lures_max_length {
            get {
                return ResourceManager.GetString("annotation_lures_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of lures must be at least one.
        /// </summary>
        public static string annotation_lures_min_length {
            get {
                return ResourceManager.GetString("annotation_lures_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_name_max_length {
            get {
                return ResourceManager.GetString("annotation_name_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field name must be filled.
        /// </summary>
        public static string annotation_name_required {
            get {
                return ResourceManager.GetString("annotation_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_neighborhood_max_length {
            get {
                return ResourceManager.GetString("annotation_neighborhood_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password should be filled.
        /// </summary>
        public static string annotation_new_password_required {
            get {
                return ResourceManager.GetString("annotation_new_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_observation_max_length {
            get {
                return ResourceManager.GetString("annotation_observation_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number must be higher than 0.
        /// </summary>
        public static string annotation_page_number_range {
            get {
                return ResourceManager.GetString("annotation_page_number_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number is required.
        /// </summary>
        public static string annotation_page_number_required {
            get {
                return ResourceManager.GetString("annotation_page_number_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size must be higher than 0.
        /// </summary>
        public static string annotation_page_size_range {
            get {
                return ResourceManager.GetString("annotation_page_size_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size is required.
        /// </summary>
        public static string annotation_page_size_required {
            get {
                return ResourceManager.GetString("annotation_page_size_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have more than 8 characters.
        /// </summary>
        public static string annotation_password_min_length {
            get {
                return ResourceManager.GetString("annotation_password_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be filled.
        /// </summary>
        public static string annotation_password_required {
            get {
                return ResourceManager.GetString("annotation_password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location difficulty rate must be filled.
        /// </summary>
        public static string annotation_rate_required {
            get {
                return ResourceManager.GetString("annotation_rate_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token must be filled.
        /// </summary>
        public static string annotation_refresh_token_required {
            get {
                return ResourceManager.GetString("annotation_refresh_token_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location risk rate must be filled.
        /// </summary>
        public static string annotation_risk_required {
            get {
                return ResourceManager.GetString("annotation_risk_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spot unique identifier must be filled.
        /// </summary>
        public static string annotation_spot_required {
            get {
                return ResourceManager.GetString("annotation_spot_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 245 has been reached.
        /// </summary>
        public static string annotation_street_max_length {
            get {
                return ResourceManager.GetString("annotation_street_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be filled.
        /// </summary>
        public static string annotation_title_required {
            get {
                return ResourceManager.GetString("annotation_title_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 5 has been reached.
        /// </summary>
        public static string annotation_token_max_length {
            get {
                return ResourceManager.GetString("annotation_token_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token must be filled.
        /// </summary>
        public static string annotation_token_required {
            get {
                return ResourceManager.GetString("annotation_token_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit measure must be filled.
        /// </summary>
        public static string annotation_unit_measure_required {
            get {
                return ResourceManager.GetString("annotation_unit_measure_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must be filled.
        /// </summary>
        public static string annotation_user_file_required {
            get {
                return ResourceManager.GetString("annotation_user_file_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 20 has been reached.
        /// </summary>
        public static string annotation_username_max_length {
            get {
                return ResourceManager.GetString("annotation_username_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight must be filled.
        /// </summary>
        public static string annotation_weight_required {
            get {
                return ResourceManager.GetString("annotation_weight_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of characters 8 has been reached.
        /// </summary>
        public static string annotation_zip_code_max_length {
            get {
                return ResourceManager.GetString("annotation_zip_code_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail already in use.
        /// </summary>
        public static string email_in_use {
            get {
                return ResourceManager.GetString("email_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is authenticated.
        /// </summary>
        public static string is_authenticated {
            get {
                return ResourceManager.GetString("is_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this code to change your password.
        /// </summary>
        public static string mail_code_description {
            get {
                return ResourceManager.GetString("mail_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FishSpot receive a request to use this email to change the password.
        /// </summary>
        public static string mail_description {
            get {
                return ResourceManager.GetString("mail_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recover.
        /// </summary>
        public static string mail_subject {
            get {
                return ResourceManager.GetString("mail_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string mail_title {
            get {
                return ResourceManager.GetString("mail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not recognize this account in the FishSpot system or did not request a password change, someone may be impersonating you.
        /// </summary>
        public static string mail_warning_description {
            get {
                return ResourceManager.GetString("mail_warning_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resources were attached to a spot.
        /// </summary>
        public static string resource_attached {
            get {
                return ResourceManager.GetString("resource_attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource was attached to user.
        /// </summary>
        public static string resource_attached_to_user {
            get {
                return ResourceManager.GetString("resource_attached_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resources were detached to a spot.
        /// </summary>
        public static string resource_detached {
            get {
                return ResourceManager.GetString("resource_detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} are allowed..
        /// </summary>
        public static string resource_file_allowed {
            get {
                return ResourceManager.GetString("resource_file_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found.
        /// </summary>
        public static string resource_file_not_found {
            get {
                return ResourceManager.GetString("resource_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string resource_not_found {
            get {
                return ResourceManager.GetString("resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was caught when tried to detach the resources.
        /// </summary>
        public static string resource_unable_to_detach {
            get {
                return ResourceManager.GetString("resource_unable_to_detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save files.
        /// </summary>
        public static string resource_unable_to_save {
            get {
                return ResourceManager.GetString("resource_unable_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot deleted successfully.
        /// </summary>
        public static string spot_deleted_successfully {
            get {
                return ResourceManager.GetString("spot_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot find.
        /// </summary>
        public static string spot_find {
            get {
                return ResourceManager.GetString("spot_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations find.
        /// </summary>
        public static string spot_location_find {
            get {
                return ResourceManager.GetString("spot_location_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot not found.
        /// </summary>
        public static string spot_not_found {
            get {
                return ResourceManager.GetString("spot_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot registered successfully.
        /// </summary>
        public static string spot_registered_successfully {
            get {
                return ResourceManager.GetString("spot_registered_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot updated successfully.
        /// </summary>
        public static string spot_updated_successfully {
            get {
                return ResourceManager.GetString("spot_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validation token was sent to your e-mail.
        /// </summary>
        public static string token_email_sent {
            get {
                return ResourceManager.GetString("token_email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        public static string token_invalid {
            get {
                return ResourceManager.GetString("token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found.
        /// </summary>
        public static string token_not_found {
            get {
                return ResourceManager.GetString("token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string token_refresh_invalid {
            get {
                return ResourceManager.GetString("token_refresh_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed.
        /// </summary>
        public static string token_refreshed {
            get {
                return ResourceManager.GetString("token_refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is valid.
        /// </summary>
        public static string token_valid {
            get {
                return ResourceManager.GetString("token_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t authorized.
        /// </summary>
        public static string unauthorized {
            get {
                return ResourceManager.GetString("unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was correctly authenticated..
        /// </summary>
        public static string user_authenticated {
            get {
                return ResourceManager.GetString("user_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life is like fishing: sometimes you catch a big fish, sometimes you come back empty-handed..
        /// </summary>
        public static string user_default_description {
            get {
                return ResourceManager.GetString("user_default_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User found successfully.
        /// </summary>
        public static string user_found_successfully {
            get {
                return ResourceManager.GetString("user_found_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to delete spot.
        /// </summary>
        public static string user_not_authorized_to_delete_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_delete_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to update spot.
        /// </summary>
        public static string user_not_authorized_to_update_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_update_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password.
        /// </summary>
        public static string user_or_password_incorrect {
            get {
                return ResourceManager.GetString("user_or_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string user_password_incorrect {
            get {
                return ResourceManager.GetString("user_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string user_register_successfully {
            get {
                return ResourceManager.GetString("user_register_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string user_updated_successfully {
            get {
                return ResourceManager.GetString("user_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already in use.
        /// </summary>
        public static string user_username_in_use {
            get {
                return ResourceManager.GetString("user_username_in_use", resourceCulture);
            }
        }
    }
}
