//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishSpotApi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FishSpotResource_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FishSpotResource_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishSpotApi.Domain.Resources.FishSpotResource.pt-BR", typeof(FishSpotResource_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já em uso.
        /// </summary>
        public static string email_in_use {
            get {
                return ResourceManager.GetString("email_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro interno do servidor.
        /// </summary>
        public static string internal_server_error {
            get {
                return ResourceManager.GetString("internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticado.
        /// </summary>
        public static string is_authenticated {
            get {
                return ResourceManager.GetString("is_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Verificação.
        /// </summary>
        public static string mail_verification_code {
            get {
                return ResourceManager.GetString("mail_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso.
        /// </summary>
        public static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O recurso foi anexado ao ponto.
        /// </summary>
        public static string resource_attached {
            get {
                return ResourceManager.GetString("resource_attached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O recurso foi desanexado do ponto.
        /// </summary>
        public static string resource_detached {
            get {
                return ResourceManager.GetString("resource_detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso não encontrado.
        /// </summary>
        public static string resource_not_found {
            get {
                return ResourceManager.GetString("resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro foi encontrado enquanto tentava desanexar os arquivos.
        /// </summary>
        public static string resource_unable_to_detach {
            get {
                return ResourceManager.GetString("resource_unable_to_detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel salvar os arquivos .
        /// </summary>
        public static string resource_unable_to_save {
            get {
                return ResourceManager.GetString("resource_unable_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto removido com sucesso.
        /// </summary>
        public static string spot_deleted_successfully {
            get {
                return ResourceManager.GetString("spot_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto encontrado.
        /// </summary>
        public static string spot_find {
            get {
                return ResourceManager.GetString("spot_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizações de pontos encontrados.
        /// </summary>
        public static string spot_location_find {
            get {
                return ResourceManager.GetString("spot_location_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto não encontrado.
        /// </summary>
        public static string spot_not_found {
            get {
                return ResourceManager.GetString("spot_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto registrado com sucesso.
        /// </summary>
        public static string spot_registered_successfully {
            get {
                return ResourceManager.GetString("spot_registered_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponto alterado com sucesso.
        /// </summary>
        public static string spot_updated_successfully {
            get {
                return ResourceManager.GetString("spot_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um token para validação foi enviado para o email.
        /// </summary>
        public static string token_email_sent {
            get {
                return ResourceManager.GetString("token_email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token não é valido.
        /// </summary>
        public static string token_invalid {
            get {
                return ResourceManager.GetString("token_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não encontrado.
        /// </summary>
        public static string token_not_found {
            get {
                return ResourceManager.GetString("token_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token para atualizar é invalido.
        /// </summary>
        public static string token_refresh_invalid {
            get {
                return ResourceManager.GetString("token_refresh_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token atualizado.
        /// </summary>
        public static string token_refreshed {
            get {
                return ResourceManager.GetString("token_refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token é valido.
        /// </summary>
        public static string token_valid {
            get {
                return ResourceManager.GetString("token_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não autorizado.
        /// </summary>
        public static string unauthorized {
            get {
                return ResourceManager.GetString("unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário corretamente autenticado.
        /// </summary>
        public static string user_authenticated {
            get {
                return ResourceManager.GetString("user_authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não é autorizado a deletar o ponto.
        /// </summary>
        public static string user_not_authorized_to_delete_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_delete_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não é autorizado para atualizar o ponto.
        /// </summary>
        public static string user_not_authorized_to_update_spot {
            get {
                return ResourceManager.GetString("user_not_authorized_to_update_spot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não esta correta.
        /// </summary>
        public static string user_password_incorrect {
            get {
                return ResourceManager.GetString("user_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário registrado com sucesso.
        /// </summary>
        public static string user_register_successfully {
            get {
                return ResourceManager.GetString("user_register_successfully", resourceCulture);
            }
        }
    }
}
